version: '3.8'

services:
  backend:
    image: ghcr.io/vrsen/agency-swarm-backend:latest
    container_name: agency-backend
    restart: always
    ports:
      - "3001:3001"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - BACKEND_PORT=3001
    depends_on:
      - frontend

  frontend:
    image: ghcr.io/vrsen/agency-swarm-frontend:latest
    container_name: agency-frontend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - backend
